### ISSUE TITLE
Add --first-branch option

### ISSUE THREAD

**Issue by meowsus** [meowsus/wagemage#5]
Or something to that effect...

Running `codeslave --branch '(-stable$|^master$)'` returns all stable branches, but often we want to commit only to the earliest branch in this list. We should take the returned list, display them all in the output, but highlight the one that will be affected by the script when this option is passed. The list should be sorted and the first chosen.

**Comment by tubbo** [comment]
Instead of having a different argument, I think this is just how `--branch` should work in general. Assuming that all changes from the earlier branches will be merged into the later branches, including `master`, we could instruct users to do: `--branch '(-stable$)'` to find the earliest stable branch that should be committed to. If you wanted the "first stable branch" sorted alphanumerically, and you included "master", you'd always get "master" because "m" comes before "v" in alphabet.

**Comment by meowsus** [comment]
When talking about Workarea plugins, specifically, we might be releasing from a master branch for a given plugin. That's why `--branch '(-stable$|^master$)'` is necessary as a branch option.

I'm thinking:

1. We always plop `master` at the end of the derived branch list
1. `--first-branch` outputs the full list of branches discovered, but highlights the first branch indicating that that one will be operated upon.
